apiVersion: v1
kind: Service
metadata:
  name: outerloop-service
spec:
  ports:
  - name: "outerloop-service"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: outerloop-service
  type: ClusterIP
